### PR TITLE
Offset date

### PR DESCRIPTION
**Pull request by mindedj**

### CODE REVIEW

**Review by nsoma97 — COMMENTED** [review]
@mindedj I like this approach. Can you please write some test cases for the new functionality? Like for example where you set the current date, and assert the expected output with and without `expect_future_day` enabled.

**Comment by mindedj** [comment]
@nsoma97 Is it fine if i leave the `test_datetime_extractor` function to test `expect_future_day` disabled as it is the default value and those tests should not fail and create a new function that tests with  `expect_future_day` enabled?

**Comment by nsoma97** [comment]
@mindedj yes, I think it's perfectly enough to extend this test function with a few lines where your functionality is enabled: https://github.com/szegedai/hun-date-parser/blob/e4952936aa7281c1cb8f882ca6706dc6ac72a78c/test/test_date_parsers.py#L70

**Comment by mindedj** [comment]
Extended the function. Please correct me if match_weekday should handle 'most'.

**Comment by nsoma97** [comment]
@mindedj no, it's fine. you can go ahead and merge it :slightly_smiling_face:

**Pull request merged**
